### ISSUE TITLE
Vertical Orientation

### ISSUE THREAD

**Issue by DennyWeinberg** [hearsilent/DiscreteSlider#1]
Hi,

that's an awesome library.

If you want to make it possible to draw it vertically, you will be much better that [the other library](https://github.com/Ramotion/fluid-slider-android) and I will used it in my app.
The bubble should appear on the right or on the left side (configurable).

**Comment by hearsilent** [comment]
I'll support it soon. Thanks for your suggestion ;)

**Comment by DennyWeinberg** [comment]
Awesome! Please keep me up to date

**Comment by hearsilent** [comment]
1.0.2 has been released. Try it!

**Comment by DennyWeinberg** [comment]
Awesome! Will try. But am a bit busy right now.

**Comment by DennyWeinberg** [comment]
Hello,

do you know that error?
`AAPT: error: duplicate value for resource 'attr/orientation' with config ''.`

is that related to the orientation you've added?
```
C:\tmp\android_build\android-photos\app\intermediates\incremental\mergePhotoMapDebugResources\merged.dir\values\values.xml: error: file failed to compile.
	at com.android.builder.internal.aapt.v2.Aapt2Exception$Companion.create(Aapt2Exception.kt:45)
	at com.android.builder.internal.aapt.v2.Aapt2Exception$Companion.create$default(Aapt2Exception.kt:39)
	at com.android.build.gradle.internal.res.Aapt2ErrorUtils.rewriteException(Aapt2ErrorUtils.kt:97)
	at com.android.build.gradle.internal.res.Aapt2ErrorUtils.rewriteCompileException(Aapt2ErrorUtils.kt:55)
	at com.android.build.gradle.internal.res.Aapt2CompileWithBlameRunnable$run$1.invoke(Aapt2CompileWithBlameRunnable.kt:39)
	at com.android.build.gradle.internal.res.Aapt2CompileWithBlameRunnable$run$1.invoke(Aapt2CompileWithBlameRunnable.kt:28)
	at com.android.build.gradle.internal.res.namespaced.Aapt2DaemonManagerService.useAaptDaemon(Aapt2DaemonManagerService.kt:71)
	at com.android.build.gradle.internal.res.namespaced.Aapt2DaemonManagerService.useAaptDaemon$default(Aapt2DaemonManagerService.kt:69)
	at com.android.build.gradle.internal.res.Aapt2CompileWithBlameRunnable.run(Aapt2CompileWithBlameRunnable.kt:34)
	at com.android.ide.common.workers.ExecutorServiceAdapter$submit$submission$1.run(ExecutorServiceAdapter.kt:40)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
C:\tmp\android_build\android-photos\app\intermediates\incremental\mergePhotoMapDebugResources\merged.dir\values\values.xml:5735: error: duplicate value for resource 'attr/orientation' with config ''.
C:\tmp\android_build\android-photos\app\intermediates\incremental\mergePhotoMapDebugResources\merged.dir\values\values.xml:5735: error: resource previously defined here.
C:\tmp\android_build\android-photos\app\intermediates\incremental\mergePhotoMapDebugResources\merged.dir\values\values.xml: error: file failed to compile.
```

**Comment by hearsilent** [comment]
@DennyWeinberg 1.0.6 has fixed this issue. Try it!

**Comment by DennyWeinberg** [comment]
Hello,

I'm still getting these errors:
```
Android resource compilation failed
C:\tmp\android_build\android-photos\app\intermediates\incremental\mergePhotoMapDebugResources\merged.dir\values\values.xml:5736: error: duplicate value for resource 'attr/orientation' with config ''.
C:\tmp\android_build\android-photos\app\intermediates\incremental\mergePhotoMapDebugResources\merged.dir\values\values.xml:5736: error: resource previously defined here.
C:\tmp\android_build\android-photos\app\intermediates\incremental\mergePhotoMapDebugResources\merged.dir\values\values.xml: error: file failed to compile.
```

I cleaned and re built the entire project. Without that line: `implementation 'com.github.hearsilent:DiscreteSlider:1.0.6'` it works.

**Comment by hearsilent** [comment]
@DennyWeinberg Sorry for that.
All attrs has prefix `ds_` from v1.0.7

**Comment by DennyWeinberg** [comment]
Works. Thanks. Now I will do some advanced tests.

**Comment by hearsilent** [comment]
You're welcome.
